version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./tcs
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_DATABASE=timing_consensus_db
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - MONGO_CLUSTER=mongodb:27017
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/timing_consensus_db?authSource=admin
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 